"""model-post-title add

Revision ID: 3268003f2af8
Revises: 51f5ccfba190
Create Date: 2016-09-05 17:53:37.923948

"""

# revision identifiers, used by Alembic.
revision = '3268003f2af8'
down_revision = '51f5ccfba190'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
