"""model-post-title add

Revision ID: 78ac40739c16
Revises: 3268003f2af8
Create Date: 2016-09-05 17:54:40.327821

"""

# revision identifiers, used by Alembic.
revision = '78ac40739c16'
down_revision = '3268003f2af8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
